// Generated by gencpp from file decomp_ros_msgs/Polyhedron.msg
// DO NOT EDIT!


#ifndef DECOMP_ROS_MSGS_MESSAGE_POLYHEDRON_H
#define DECOMP_ROS_MSGS_MESSAGE_POLYHEDRON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace decomp_ros_msgs
{
template <class ContainerAllocator>
struct Polyhedron_
{
  typedef Polyhedron_<ContainerAllocator> Type;

  Polyhedron_()
    : points()
    , normals()  {
    }
  Polyhedron_(const ContainerAllocator& _alloc)
    : points(_alloc)
    , normals(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points_type;
  _points_type points;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _normals_type;
  _normals_type normals;





  typedef boost::shared_ptr< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> const> ConstPtr;

}; // struct Polyhedron_

typedef ::decomp_ros_msgs::Polyhedron_<std::allocator<void> > Polyhedron;

typedef boost::shared_ptr< ::decomp_ros_msgs::Polyhedron > PolyhedronPtr;
typedef boost::shared_ptr< ::decomp_ros_msgs::Polyhedron const> PolyhedronConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::decomp_ros_msgs::Polyhedron_<ContainerAllocator1> & lhs, const ::decomp_ros_msgs::Polyhedron_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points &&
    lhs.normals == rhs.normals;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::decomp_ros_msgs::Polyhedron_<ContainerAllocator1> & lhs, const ::decomp_ros_msgs::Polyhedron_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace decomp_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30e67f500a403ad4875ae4600d46dde5";
  }

  static const char* value(const ::decomp_ros_msgs::Polyhedron_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30e67f500a403ad4ULL;
  static const uint64_t static_value2 = 0x875ae4600d46dde5ULL;
};

template<class ContainerAllocator>
struct DataType< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decomp_ros_msgs/Polyhedron";
  }

  static const char* value(const ::decomp_ros_msgs::Polyhedron_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] points\n"
"geometry_msgs/Point[] normals #norm is an outer vector\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::decomp_ros_msgs::Polyhedron_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
      stream.next(m.normals);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Polyhedron_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decomp_ros_msgs::Polyhedron_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decomp_ros_msgs::Polyhedron_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "normals[]" << std::endl;
    for (size_t i = 0; i < v.normals.size(); ++i)
    {
      s << indent << "  normals[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.normals[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECOMP_ROS_MSGS_MESSAGE_POLYHEDRON_H
